/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPlantationsIndexRouteImport } from './routes/dashboard/plantations/index'
import { Route as DashboardOverviewIndexRouteImport } from './routes/dashboard/overview/index'
import { Route as DashboardMonitoringStatisticsIndexRouteImport } from './routes/dashboard/monitoring/statistics/index'
import { Route as DashboardMonitoringHarvestIndexRouteImport } from './routes/dashboard/monitoring/harvest/index'
import { Route as DashboardMonitoringEnvironmentIndexRouteImport } from './routes/dashboard/monitoring/environment/index'
import { Route as DashboardMonitoringDistributionIndexRouteImport } from './routes/dashboard/monitoring/distribution/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPlantationsIndexRoute =
  DashboardPlantationsIndexRouteImport.update({
    id: '/plantations/',
    path: '/plantations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardOverviewIndexRoute = DashboardOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringStatisticsIndexRoute =
  DashboardMonitoringStatisticsIndexRouteImport.update({
    id: '/monitoring/statistics/',
    path: '/monitoring/statistics/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMonitoringHarvestIndexRoute =
  DashboardMonitoringHarvestIndexRouteImport.update({
    id: '/monitoring/harvest/',
    path: '/monitoring/harvest/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMonitoringEnvironmentIndexRoute =
  DashboardMonitoringEnvironmentIndexRouteImport.update({
    id: '/monitoring/environment/',
    path: '/monitoring/environment/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMonitoringDistributionIndexRoute =
  DashboardMonitoringDistributionIndexRouteImport.update({
    id: '/monitoring/distribution/',
    path: '/monitoring/distribution/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/overview': typeof DashboardOverviewIndexRoute
  '/dashboard/plantations': typeof DashboardPlantationsIndexRoute
  '/dashboard/monitoring/distribution': typeof DashboardMonitoringDistributionIndexRoute
  '/dashboard/monitoring/environment': typeof DashboardMonitoringEnvironmentIndexRoute
  '/dashboard/monitoring/harvest': typeof DashboardMonitoringHarvestIndexRoute
  '/dashboard/monitoring/statistics': typeof DashboardMonitoringStatisticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/overview': typeof DashboardOverviewIndexRoute
  '/dashboard/plantations': typeof DashboardPlantationsIndexRoute
  '/dashboard/monitoring/distribution': typeof DashboardMonitoringDistributionIndexRoute
  '/dashboard/monitoring/environment': typeof DashboardMonitoringEnvironmentIndexRoute
  '/dashboard/monitoring/harvest': typeof DashboardMonitoringHarvestIndexRoute
  '/dashboard/monitoring/statistics': typeof DashboardMonitoringStatisticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/overview/': typeof DashboardOverviewIndexRoute
  '/dashboard/plantations/': typeof DashboardPlantationsIndexRoute
  '/dashboard/monitoring/distribution/': typeof DashboardMonitoringDistributionIndexRoute
  '/dashboard/monitoring/environment/': typeof DashboardMonitoringEnvironmentIndexRoute
  '/dashboard/monitoring/harvest/': typeof DashboardMonitoringHarvestIndexRoute
  '/dashboard/monitoring/statistics/': typeof DashboardMonitoringStatisticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/overview'
    | '/dashboard/plantations'
    | '/dashboard/monitoring/distribution'
    | '/dashboard/monitoring/environment'
    | '/dashboard/monitoring/harvest'
    | '/dashboard/monitoring/statistics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/overview'
    | '/dashboard/plantations'
    | '/dashboard/monitoring/distribution'
    | '/dashboard/monitoring/environment'
    | '/dashboard/monitoring/harvest'
    | '/dashboard/monitoring/statistics'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/overview/'
    | '/dashboard/plantations/'
    | '/dashboard/monitoring/distribution/'
    | '/dashboard/monitoring/environment/'
    | '/dashboard/monitoring/harvest/'
    | '/dashboard/monitoring/statistics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/plantations/': {
      id: '/dashboard/plantations/'
      path: '/plantations'
      fullPath: '/dashboard/plantations'
      preLoaderRoute: typeof DashboardPlantationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview/': {
      id: '/dashboard/overview/'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring/statistics/': {
      id: '/dashboard/monitoring/statistics/'
      path: '/monitoring/statistics'
      fullPath: '/dashboard/monitoring/statistics'
      preLoaderRoute: typeof DashboardMonitoringStatisticsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring/harvest/': {
      id: '/dashboard/monitoring/harvest/'
      path: '/monitoring/harvest'
      fullPath: '/dashboard/monitoring/harvest'
      preLoaderRoute: typeof DashboardMonitoringHarvestIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring/environment/': {
      id: '/dashboard/monitoring/environment/'
      path: '/monitoring/environment'
      fullPath: '/dashboard/monitoring/environment'
      preLoaderRoute: typeof DashboardMonitoringEnvironmentIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/monitoring/distribution/': {
      id: '/dashboard/monitoring/distribution/'
      path: '/monitoring/distribution'
      fullPath: '/dashboard/monitoring/distribution'
      preLoaderRoute: typeof DashboardMonitoringDistributionIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardOverviewIndexRoute: typeof DashboardOverviewIndexRoute
  DashboardPlantationsIndexRoute: typeof DashboardPlantationsIndexRoute
  DashboardMonitoringDistributionIndexRoute: typeof DashboardMonitoringDistributionIndexRoute
  DashboardMonitoringEnvironmentIndexRoute: typeof DashboardMonitoringEnvironmentIndexRoute
  DashboardMonitoringHarvestIndexRoute: typeof DashboardMonitoringHarvestIndexRoute
  DashboardMonitoringStatisticsIndexRoute: typeof DashboardMonitoringStatisticsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardOverviewIndexRoute: DashboardOverviewIndexRoute,
  DashboardPlantationsIndexRoute: DashboardPlantationsIndexRoute,
  DashboardMonitoringDistributionIndexRoute:
    DashboardMonitoringDistributionIndexRoute,
  DashboardMonitoringEnvironmentIndexRoute:
    DashboardMonitoringEnvironmentIndexRoute,
  DashboardMonitoringHarvestIndexRoute: DashboardMonitoringHarvestIndexRoute,
  DashboardMonitoringStatisticsIndexRoute:
    DashboardMonitoringStatisticsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
